=== Cozma-Catalin/CursJavaSDA/CursJavaPractic/codeWars/src/main/resources/PROGRAMATORS.dtd
<!ELEMENT PROGRAMATORS (PROGRAMATOR+)>
        <!ELEMENT PROGRAMATOR (PERSON+)>
        <!ELEMENT PERSON (NAME,SEX,DOB,ADDRESS)>
        <!ELEMENT NAME (#PCDATA)>
        <!ELEMENT SEX (#PCDATA)>
        <!ELEMENT DOB (DATE?)>
        <!ELEMENT ADDRESS (STREET,CITY)>
        <!ELEMENT STREET (#PCDATA)>
        <!ELEMENT CITY (#PCDATA)>
        <!ELEMENT DATE (DAY,MONTH,YEAR)>
        <!ELEMENT DAY (#PCDATA)>
        <!ELEMENT MONTH (#PCDATA)>
        <!ELEMENT YEAR (#PCDATA)>


        <!ATTLIST PROGRAMATOR LANG CDATA #REQUIRED>

=== Cozma-Catalin/CursJavaSDA/CursJavaPractic/codeWars/target/classes/PROGRAMATORS.xml
<?xml version="1.0" encoding = "UTF-8"?>
<!DOCTYPE PROGRAMATORS SYSTEM "PROGRAMATORS.dtd">

<PROGRAMATORS>
    <PROGRAMATOR LANG="JAVA">
        <PERSON>
            <NAME>COZMA CATALIN</NAME>
            <SEX>M</SEX>
            <DOB>
                <DATE>
                    <DAY>09</DAY>
                    <MONTH>02</MONTH>
                    <YEAR>1989</YEAR>
                </DATE>
            </DOB>
            <ADDRESS>
                <STREET>CALUGARENI</STREET>
                <CITY>GALATI</CITY>
            </ADDRESS>
        </PERSON>
    </PROGRAMATOR>

    <PROGRAMATOR LANG="PYTHON">
        <PERSON>
            <NAME>COZMA MARIAN</NAME>
            <SEX>M</SEX>
            <DOB>
                <DATE>
                    <DAY>29</DAY>
                    <MONTH>06</MONTH>
                    <YEAR>1987</YEAR>
                </DATE>
            </DOB>
            <ADDRESS>
                <STREET>ALEEA TOMESTI</STREET>
                <CITY>BUCURESTI</CITY>
            </ADDRESS>
        </PERSON>
    </PROGRAMATOR>
</PROGRAMATORS>
